name: Deploy Backend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted   # your Azure VM runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd /var/www/backend
          rsync -av --delete $GITHUB_WORKSPACE/ /var/www/backend/
          cd /var/www/backend
          npm install --production

      - name: Restart backend with PM2
        run: |
          pm2 delete backend || true
          pm2 start server.js --name backend
          pm2 save
